# Generated by Django 2.2.4 on 2019-08-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField(blank=True, null=True)),
                ('class_name', models.CharField(blank=True, max_length=200, null=True)),
                ('book_name', models.CharField(blank=True, max_length=200, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoldBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField(blank=True, null=True)),
                ('class_name', models.CharField(blank=True, max_length=200, null=True)),
                ('book_name', models.CharField(blank=True, max_length=200, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sold_price', models.IntegerField(blank=True, null=True)),
                ('customer_feedback', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
